InsightSoftwareConsortium/ITK-Wasm

.circleci/config.yml
chrome is now used for the browser tests
=> chore(ci): Output chrome instead of firefox version

build.js
=> docs(Build): Provide helpful error message when docker is not available

src/WebWorkers/ImageIOWorker.js
This improves how the error is handled downstream and improves the message.
=> fix(ImageIOWorker): Wrap the returned errors in a Promise

doc/content/examples/node.md, doc/content/examples/webpack.md, doc/tpl/__en__, doc/tpl/__sidebar__, examples/Webpack/.babelrc, examples/Webpack/dist/index.html, examples/Webpack/karma.conf.js, examples/Webpack/package-lock.json, examples/Webpack/package.json, examples/Webpack/src/index.js, examples/Webpack/test/config/itkConfigTest.js, examples/Webpack/test/index.js, examples/Webpack/webpack.config.js
@agirault It turns out we cannot bundle the web workers because of [a bug](https://github.com/webpack-contrib/worker-loader/issues/45) in `worker-loader`.
=> feat(Examples): Add Webpack example

build.js
This is required for create-react-app app's in optimized mode.
=> build(package): Transpile sources to ES5

src/readImageArrayBuffer.js
Image is not properly returned from webworker.
Addresses latest comment in https://github.com/InsightSoftwareConsortium/itk-js/issues/128#issuecomment-388673341
=> fix(readImageArrayBuffer): Return webworker promise

build.js
When invoking the build with:
git clean -fdx
npm install
npm run build -- --debug
Emscripten modules will be built in debug mode, i.e. the JavaScript is
not minified, and it is easier to read and debug.
=> feat(build.js): Add --debug flag to build Emscripten modules in debug

src/Docker/itk-js-base/Dockerfile
Addresses final VXL warnings (hooray!).
Bring in modular FreeSurfer mesh module.
=> feat(Dependencies): Bump ITK to 2018-12-16 master

package-lock.json, src/itk-js-cli.js
Prevents printing out the cli helps on success.
=> fix(cli): Always exit with the Docker run return code

.gitignore, build.js, src/Docker/itk-js-vtk/Dockerfile, src/IOTypes.js, src/runPipelineEmscripten.js, test/WriteVTKPolyDataPipeline/CMakeLists.txt, test/WriteVTKPolyDataPipeline/WriteVTKPolyData.cxx, test/runPipelineNodeTest.js
@jourdain @aylward @floryst @wschroed @jcfr vtkPolyData write support WIP!
=> feat(runPipelineNode): Add vtkPolyData write support

doc/content/api/Image.md, doc/content/api/node_pipelines.md, src/WebWorkers/Pipeline.worker.js, test/Browser/runPipelineBrowserTest.js
@jourdain @floryst @agirault @jcfr
=> vtk.js PolyData browser pipeline support

.circleci/config.yml, .gitignore, examples/UMD/README.md, examples/UMD/dist/index.html, examples/UMD/dist/index.js, examples/UMD/karma.conf.js, examples/UMD/package.json, examples/UMD/test/index.js, examples/UMD/test/run.sh, examples/UnpkgIO/README.md
=> doc(Examples): Add UMD example

examples/UMD/dist/index.html, examples/UMD/dist/index.js, examples/UMD/dist/styles.css, examples/Webpack/dist/index.html, examples/Webpack/dist/styles.css, examples/Webpack/src/index.js
=> Improve glitch examples

examples/Node.js/package.json
=> fix(Node.jsExample): Bump ITK version dependency

examples/UMD/dist/index.html, examples/UMD/dist/index.js, examples/UMD/dist/styles.css, examples/UMD/karma.conf.js, examples/UMD/package.json, examples/UMD/test/index.js, examples/UnpkgIO/dist/index.html, examples/UnpkgIO/package.json, examples/UnpkgIO/src/index.js, examples/UnpkgIO/test/index.js, examples/Webpack/dist/styles.css, examples/Webpack/package.json, examples/Webpack/src/index.js, examples/Webpack/test/index.js
=> Example mesh

doc/content/api/Image.md
=> doc(Image): Add note about indexing convention

.circleci/config.yml
Attempt to address configuration format complaints.
=> ci(Circle): Be explicit about ignored branches

.github/workflows/release-notes.yml, doc/release-introduction.md
=> build(Release): Add Release Notes GitHub Action

.github/workflows/release-notes.yml
To address:
/home/runner/work/_temp/1334a765-77b5-4d8c-8618-7cf0b1ae0e1e.sh: line 4: conventional-changelog: command not found
11
=> ci(ReleaseNotes): Use npx for conventional-changelog execution

karma.conf.js, package-lock.json, package.json
For consistency and to reduce testing environment dependencies.
=> build(Karma): Use puppeteer for Chrome

src/Bindings/itkDICOMImageSeriesReaderJSBinding.cxx, src/CMakeLists.txt, test/Browser/DICOMSeriesTest.js, test/DICOMSeriesTest.js
=> feat(readImageDICOMFileSeries): Use GDCM instead of DCMTK

.babelrc, package-lock.json, package.json, src/readImageDICOMFileSeries.js
For dependencies. See:
https://www.npmjs.com/package/regenerator-runtime
https://babeljs.io/docs/en/babel-plugin-transform-runtime/
=> fix(Build): import Babel's regenerator runtime

.github/workflows/release-notes.yml, src/EmscriptenModule/itkJSImageIOPre.js.in, src/EmscriptenModule/itkJSMeshIOPre.js.in, src/EmscriptenModule/itkJSPipelinePre.js.in, src/EmscriptenModule/itkJSPolyDataIOPre.js.in
Defined in recent Emscripten and useful when the modules are distributed
on Unpkg.io or other CDN's.
=> fix(EmscriptenModule): Add prefix to locateFile

.github/workflows/release-notes.yml, package-lock.json, package.json
From "refs/tags/v12.3.0" to "v12.3.0".
=> ci(ReleaseAction): Improve tag identification

src/Docker/itk-js/ITKBridgeJavaScript.cmake, src/EmscriptenModule/itkJSImageIOPre.js.in, src/EmscriptenModule/itkJSMeshIOPre.js.in, src/EmscriptenModule/itkJSPipelinePre.js.in, src/EmscriptenModule/itkJSPolyDataIOPre.js.in, src/loadEmscriptenModuleBrowser.js
The self.location.ref is lost as a "blob:" url with importScripts so
pass in the moduleScriptDir as an initialization argument.
=> fix(loadEmscriptenModuleBrowser): Locate .wasm files from web workers

examples/UnpkgIO/dist/index.html, examples/UnpkgIO/package-lock.json, examples/UnpkgIO/package.json, examples/UnpkgIO/src/index.js, examples/Webpack/dist/index.html, examples/Webpack/dist/styles.css, examples/Webpack/package.json, examples/Webpack/src/index.js
=> Example updates

src/WorkerPool.js
This is a correct / robust follow-up to
0657b58f0c52a5579d38a957d4c40a75e1081002
=> fix(WorkerPool): info.postponed at timeout completion

package-lock.json, package.json
=> fix(deps): Bump axios version for SSRF vulnerability fix

include/itkImageIOBaseJSBinding.hxx, include/itkMeshIOBaseJSBinding.hxx, package-lock.json, package.json, src/Bindings/itkDICOMImageSeriesReaderJSBinding.cxx, src/bufferToTypedArray.js
=> fix(bufferToTypedArray): Add 64 bit integer array support

src/readDICOMTags.js
Applied with npx standard --fix src/readDICOMTags.js.
=> style(readDICOMTags): Update to make standard lint check pass

src/itk-js-cli.js
- fix(itk-js-cli): Correct default docker image tag
- fix(itk-js-cli): Print error information when dockcross initialization fails
=> default cli image

doc/content/examples/hello_world_node.md
=> doc(HelloWorld): Remove fs-extra from dependencies

src/core/internal/createWebWorkerPromise.ts, src/io/readImageDICOMFileSeries.ts, src/web-workers/image-io-operations.ts, src/web-workers/image-io.worker.ts, src/web-workers/pipeline.worker.ts
- refactor(redaImageDICOMFileSeries): Run in pipeline.worker
- build(createWebWorkerPromise): Use min bundles
=> read dicom series pipeline

dist/polydata-io/index.js, src/CMakeLists.txt, src/io/internal/bindings/image-io.package.json.in, src/io/internal/bindings/mesh-io.package.json.in, src/io/internal/bindings/polydata-io.package.json.in, src/io/internal/pipelines/image/ConvertImage/CMakeLists.txt
=> feat(io-packages): Add main entry to help WebPack

doc/content/examples/webpack.md, examples/Webpack/karma.conf.js, examples/Webpack/package.json, examples/Webpack/webpack.config.js
- doc(WebPackExample): Update for itk-wasm
=> webpack local

doc/content/docs/itk_js_to_itk_wasm_migration_guide.md, examples/Webpack/src/index.js, package.json
See:
- https://nodejs.org/api/packages.html#exports-sugar
- https://github.com/parcel-bundler/parcel/issues/4155
Suggested-by: Federico Zivolo <federico.zivolo@gmail.com>
=> feat(package.json): Add export maps

package.json
=> build(package.json): Remove index.d.ts entry from exports

include/itkOutputPolyData.h, src/pipeline/internal/runPipelineEmscripten.ts
- fix(runPipelineEmscripten): PolyData output array indexes
- fix(OutputPolyData): Correct output pointsSize
=> polydata types

examples/UMD/package-lock.json, examples/UMD/package.json
- ci(UMDExample): Increase timeout
- build(UMDExample): Bump Cypress to 9.5.2
=> umd example timeout

include/itkImportVectorImageFilter.h, include/itkImportVectorImageFilter.hxx, include/itkSupportInputImageTypes.h, include/itkSupportInputImageTypesNoVectorImage.h, include/itkWASMImageToImageFilter.hxx, src/CMakeLists.txt, src/itkSupportInputImageTypesNoVectorImage.cxx
- feat(ImportVectorImageFilter): Initial addition
- feat(WASMImageToImageFilter): VectorImage support
=> vector image support

include/itkWASMMeshToMeshFilter.hxx
- build(WASMMeshToMeshFilter): Address shadowing numberOfPoints
- build(WASMMeshToMeshFilter): Comment unused variables
=> shadow unused

.npmignore
=> build(NPMPackage): Exclude doc/

include/itkPipeline.h, include/itkSupportInputImageTypes.h, include/itkSupportInputImageTypesNoVectorImage.h, include/itkSupportInputMeshTypes.h, include/itkSupportInputPolyDataTypes.h, src/itkPipeline.cxx
For WASI, which does not currently support exceptions, and with
itk::wasm::SupportInput*Types.
=> feat(Pipeline): Shortcut help output

.github/workflows/javascript-typescript.yml, package-lock.json, package.json
This MR adds the semantic-release configuration to itk-wasm. The configuration details are provided below.
- Merges and commits to the `release` branch will publish to the default distribution channel, i.e. `npm install itk-wasm`. The tag format is `itk-wasm-v{version}`.
- After this MR, adding a commit to the `release` branch will release itk-wasm v1.0.0.
- Merges and commits to the `master` branch will publish to the beta distribution channel, i.e. `npm install itk-wasm@beta`. The tag format is `itk-wasm-v{version}.b{betaVersion}`.
- After this MR, adding a major/minor/patch commit to the `master` branch will release itk-wasm v1.0.0.b9, since the current beta version is b8.
- Semantic release will only run on the `master`, `release`, and any designated maintenance branches.
- There is …
=> Release config

.github/workflows/pr-checks.yml, package-lock.json, package.json
Adds commitlint, enforcing a commit message style.
=> chore(github): add commitlint to github actions

package.json, src/itkPipeline.cxx
- test(DefaultCommand): Fix cypress chrome / firefox invocation
- fix(Pipeline): Always use terminal colors with WASI
=> wasi colors

package-lock.json, package.json, src/itk-wasm-cli.js, src/itkConfig.ts, src/itkConfigDevelopment.ts
- feat(itk-wasm-cli): Update default Docker image for 1.0.0-b.18
- feat(version): Bump version to 1.0.0-b.18
=> bump wasm packages

package-lock.json, package.json, update-versions.cjs
This adds support for automatically publishing the `itk-*-io` packages. FYI @jadh4v
=> chore: publish io packages

src/python/itkwasm/image.py
=> BUG: Add name entry to Python itkwasm Image

.github/workflows/cypress.yml, package-lock.json, package.json, src/core/internal/createWebWorkerPromise.ts
- style(createWebWorkerPromise): Apply prettier
- chore(Dependencies): Bump Cypress to 10.6.0
=> cypress bump

dist/dicom/package.json, examples/node-js/package.json, examples/umd/package.json, examples/vite/package.json, examples/webpack/package.json, src/io/internal/packages/image-io.package.json.in, src/io/internal/packages/mesh-io.package.json.in
=> fix(package.json): Remove git+ protocol from repository url's

doc/content/docs/hacking_itk_wasm.md, doc/content/examples/debugging.md
- docs(Hacking): Document creating a debug build
- docs(Hacking): Add welcome message, semantic-release link
- docs(debugging): Fix links
=> debugging docs

dist/dicom/package.json
We should eventually automate via CI.
=> chore(itk-dicom): Bump version to 0.1.0

.github/workflows/cypress.yml, .github/workflows/examples.yml
xref: https://github.com/cypress-io/cypress/issues/23897
=> ci(Firefox): Disable until issues with FF 105 addressed:

CMakeLists.txt, src/io/internal/pipelines/common/compress-stringify/CMakeLists.txt
=> build: Export cpp-base64 from WebAssemblyInterface

BREAKING_CHANGES.md
This manually maintained files help document breaking changes in the 1.0 beta pre-release phase.
Breaking changes also continue to be noted with `BREAKING CHANGE:` in commit messages according to the conventional-changelog angular specification.
=> docs: Add BREAKING_CHANGES.md to track beta breaking changes

doc/content/docs/itk_js_to_itk_wasm_migration_guide.md, doc/content/examples/hello_world.md, doc/content/examples/index.md
I will expand this PR as I follow along and notice documentation issues.
=> Documentation updates

cypress/e2e/pipeline/runPipeline.cy.ts, src/pipeline/runPipeline.ts, src/web-workers/RunPipelineInput.ts, src/web-workers/pipeline.worker.ts
We do not have to use itkConfig.
=> feat(runPipeline): Support passing pipelineBaseUrl directly

doc/content/examples/vite.md, examples/vite/README.md, examples/vite/cypress/e2e/load_data.cy.js, examples/vite/package-lock.json, examples/vite/package.json, examples/vite/vite.config.js
We need to use vite-plugin-static-copy per: https://github.com/vitejs/vite/issues/6696https://github.com/vitejs/vite/issues/6696
Also update dependencies, use a different port.
=> docs(ViteExample): Update to Vite 4.0.4

src/core/createWebWorkerPromise.ts, src/pipeline/runPipeline.ts
Adds the ability to use a bundler vendored pipeline worker.
=> feat(runPipeline): Support passing null pipelineWorkerUrl

.github/workflows/cxx-python.yml
Issue tracked here: https://github.com/Kitware/KWStyle/issues/107
=> build: Ignore sprintf warnings

docs/api/index.html, docs/docs/index.html, docs/examples/index.html, docs/tutorial/index.html
Workaround if we cannot use redirect rules re:
https://github.com/FleekHQ/fleek-docs/issues/154 .
=> docs(docsify): Add redirects for shared links

src/itk-wasm-cli.js
=> feat(CLI): Add docker pull status information when required

docs/tutorial/hello_world.md
Better output when downloading the docker image.
=> docs(hello_world): Bump itk-wasm version

src/itk-wasm-cli.js
=> build(cli): Use wasi-build/ as default build dir for wasi images

include/itkWasmImageToImageFilter.hxx, package.json
For VariableLengthVector support
=> fix(itkWasmImageToImageFilter): use PixelType instead of IOPixelType

src/itk-wasm-cli.js
@PaulHax this adds your fixes to the default image.
=> feat(itk-wasm-cli): Update default Docker image for 20230310-691ddf0e

src/itk-wasm-cli.js
=> fix(cli): Fix the cmakeargs for windows

packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/itkwasm/js_package_config.py, packages/core/python/itkwasm/test/test_js_package_config.py
=> feat(Python): Add JsPackageConfig

src/itk-wasm-cli.js
Addresses:
> ERROR: Unknown option "--args,-e"
Reported in #781.
=> fix(CLI): Run invocation on Windows

docs/tutorial/hello_world.md, examples/hello-world/index.html, examples/hello-world/package-lock.json, examples/hello-world/package.json
=> docs(hello-world): Update for Windows support

packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-wasi/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/python/itkwasm/pyproject.toml, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, packages/dicom/python/itkwasm-dicom-wasi/pyproject.toml, packages/dicom/python/itkwasm-dicom/pyproject.toml
Update itkwasm Home url to the Python Sphinx documentation.
=> docs: Add Python package project.urls

packages/core/python/itkwasm/itkwasm/pipeline.py
Encapsulates the store for a run and related instance functions and helper methods.
Closes #856.
=> refactor(PythonPipeline): create and use RunInstance class

.github/workflows/cypress.yml, .github/workflows/examples.yml, .github/workflows/toolchains.yml
- ci(actions): Make the download/upload artifact versions consistent
- ci(actions): Make the `cypress-io` action versions consistent
=> ci(actions): Make actions versions consistent

.github/workflows/javascript-typescript.yml
Running out of disk space on the test stage.
=> ci: clear more disk space for js-ts build

src/bindgen/typescript/demo/all-demo-types-supported.js, src/bindgen/typescript/demo/input-parameters-demo-html.js, src/bindgen/typescript/demo/input-parameters-demo-typescript.js, src/bindgen/typescript/demo/interface-functions-demo-typescript.js, src/bindgen/typescript/demo/output-demo-html.js, src/bindgen/typescript/function-module.js, src/bindgen/typescript/resources/demo-app/utilities.js
Also copy input images before execution ro repeated execution without detached buffers.
Remove unused BinaryStream imports in function modules.
=> fix(bindgen): support multiple int, float inputs in demo app

src/pipeline/internal/runPipelineEmscripten.ts, test/node/pipeline/runPipelineNodeTest.js
Should not have been removed in
67c952d6ab28180fe600b7b4c4d78b9cd1dbadf7.
=> fix(runPipelineEmscripten): need PipelineInput .data property

packages/compare-images/typescript/src/index-node.ts, packages/compare-images/typescript/src/index.ts, packages/compress-stringify/typescript/src/index-node.ts, packages/compress-stringify/typescript/src/index.ts, packages/dicom/typescript/src/index-node.ts, packages/dicom/typescript/src/index.ts, src/bindgen/typescript/function-module.js, src/bindgen/typescript/typescript-bindings.js
=> feat(bindgen): export used interface types

packages/compare-images/typescript/cypress.config.ts, packages/compare-images/typescript/package.json, packages/compress-stringify/typescript/package-lock.json, packages/compress-stringify/typescript/package.json, packages/dicom/typescript/package.json, src/bindgen/typescript/resources/template.package.json
- test(compare-images); increase cypress timeout to 8000
- perf: bump packages to itk-wasm 1.0.0-b.136
=> package zstd

examples/mean-squares-versor-registration/package.json
Addresses the:
> Unexpected "usePreRun"
build issue.
=> build: update build image for mean-squares-versor-registration example

packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images-wasi/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-wasi/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/pyproject.toml, packages/core/python/itkwasm/test/test-accelerator/pyproject.toml, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, packages/dicom/python/itkwasm-dicom-wasi/pyproject.toml, packages/dicom/python/itkwasm-dicom/pyproject.toml, src/bindgen/python/resources/template.pyproject.toml
=> build(python): update to to wasmtime>=13.0.2

packages/compare-images/python/itkwasm-compare-images/docs/requirements.txt, packages/compress-stringify/python/itkwasm-compress-stringify/docs/requirements.txt, packages/dicom/python/itkwasm-dicom/docs/requirements.txt, src/bindgen/python/resources/docs/requirements.txt
Re: https://github.com/sphinx-extensions2/sphinx-autodoc2/issues/31
=> build: constrain astroid<3 for sphinx autodoc2 in packages

.github/workflows/python-wasm.yml, packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/python/itkwasm/pyproject.toml, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, src/bindgen/python/package-py-project-toml.js
=> ci(pyodide): bump version to 0.24.1

packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/dicom/python/itkwasm-dicom/pyproject.toml, src/bindgen/python/package-py-project-toml.js, src/bindgen/python/resources/template.pyproject.toml
=> feat(bindgen): add pyproject.toml short description for wheel summary

CMake/BuildZstd.cmake, packages/compress-stringify/BuildZstd.cmake, packages/image-io/BuildZstd.cmake, src/itk-wasm-cli.js
=> chore(zstd): bump version to 1.5.5

docs/conf.py
And point autodoc2 to the core Python package root.
=> docs: update docs path for migration to top level

packages/image-io/typescript/README.md
=> docs: update image-io typescript README

src/bindgen/typescript/resources/pipeline-worker-url.ts, src/bindgen/typescript/resources/pipelines-base-url.ts, src/bindgen/typescript/write-support-files.js
Also add writeIfOverrideNotPresent support.
=> fix(bindgen): local package.json path in pipelines-base-url.ts

packages/image-io/typescript/src/index.ts, packages/image-io/write-image.cxx
=> image-io: Export extensionToImageIo map. Avoid direction matrix transpose

.changeset/config.json, package.json, pnpm-lock.yaml
With:
```sh
pnpm add -Dw @changesets/cli
pnpm changeset init
```
Following https://pnpm.io/using-changesets.
=> feat: add changeset configuration

packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/itkwasm/pipeline.py, packages/core/python/itkwasm/pyproject.toml, packages/core/python/itkwasm/test/test_pipeline.py
dask.Array, cupy array's, etc. in addition to numpy.ndarray.
=> fix(python): support numpy ArrayLike's as inputs

docs/development/hacking_itk_wasm.md, docs/introduction/parts.md
=> docs: update contributing docs for pnpm transition

packages/core/typescript/itk-wasm/src/bindgen/python/bindgen-resource.js, packages/core/typescript/itk-wasm/src/bindgen/typescript/typescript-bindings.js, packages/core/typescript/itk-wasm/src/index-common.ts
- fix(bindgen): support resource path identification on Windows
- build: add missing setMatrixElement export
=> windows resource

packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/itkwasm/to_cupy_array.py
The distribution can be "cupy_cuda11x", etc. so just try the import.
=> fix(itkwasm): fix check for cupy

docs/python/itk_python.md
Suggested-by: Gregory Lee <grlee77@gmail.com>
=> docs(python): dict_from_<type>

packages/compare-images/typescript/package.json, packages/compress-stringify/typescript/package.json, packages/dicom/typescript/package.json, packages/downsample/typescript/package.json, packages/image-io/typescript/package.json, packages/mesh-io/typescript/package.json
Publish Windows node wasm path fixes.
=> chore(typescript): update package versions for Windows node fixes

.github/workflows/python-wasm.yml
Hopefully faster and more reliable.
=> ci: test Python wasm with ARM macOS

packages/compare-images/environment.yml, packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images-wasi/README.md, packages/compare-images/python/itkwasm-compare-images-wasi/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/template.package.json, pyproject.toml
- chore(itk-wasm): bump version to 1.0.0-b.173
- chore(pyproject): bump version to 1.0b173
=> version bump

packages/core/typescript/itk-wasm/package.json, pnpm-lock.yaml
Brings in: https://github.com/thewtex/zstddec-wasm/commit/b7139e3c1b225c44ed8afb7fc1a51953ef8f9ed1
=> build: bump @thewtex/zstddec to 0.2.1 to remove duplicate "type"

packages/core/typescript/demo-app/package.json, packages/dicom/typescript/vite.config.js, pnpm-lock.yaml
Fixes ouput image view of `readImageDicomFileSeries` pipeline with sample image inputs.
=> build(demo-app): bump version so slice view shows thin axis

packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/python/itkwasm/pyproject.toml, packages/core/typescript/itk-wasm/src/bindgen/python/package-py-project-toml.js, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, packages/downsample/python/itkwasm-downsample-emscripten/pyproject.toml, packages/image-io/python/itkwasm-image-io-emscripten/pyproject.toml, packages/image-io/python/itkwasm-image-io/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io-emscripten/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io/pyproject.toml
=> test(pyodide): bump version to 0.25.1

examples/inputs-outputs/package.json, examples/inputs-outputs/typescript/package.json, examples/mean-squares-versor-registration/package.json, examples/mean-squares-versor-registration/typescript/package.json, package.json, packages/compare-images/package.json, packages/compare-images/typescript/package.json, packages/compare-meshes/package.json, packages/compare-meshes/typescript/package.json, packages/compress-stringify/package.json, packages/compress-stringify/typescript/package.json, packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/demo-app/package.json, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/test/pipelines/typescript/package.json, packages/dicom/package.json, packages/dicom/typescript/package.json, packages/downsample/package.json, packages/downsample/typescript/package.json, packages/image-io/package.json, packages/image-io/typescript/package.json, packages/mesh-io/package.json, packages/mesh-io/typescript/package.json, pnpm-lock.yaml
- **chore(pnpm): bump version to 9.2.0**
- **chore: bump cypress, ava, start-server-and-test to latest**
=> pnpm 9.2.0

.github/workflows/cypress.yml
=> ci: use unique matrix-based name for cypress screenshots, videos

packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, src/itkjsonFromIOComponentEnum.cxx
- fix(jsonFromIOComponentEnum): add missing LONG and ULONG entries
- feat(itk-wasm-cli): Update default Docker image for 20240714-c8dabc4b
=> long ulong json

docs/introduction/packages.md
=> docs: update packages links for GitHub Org rename

packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/version.ts, packages/core/typescript/itk-wasm/test/node/pipeline/run-pipeline-node-test.js
- style(run-pipeline-node-test): prettier
- chore(itk-wasm): bump typescript package to 1.0.0-b.177
=> itk wasm bump

dev-utils/itk-wasm-native-build.sh, dev-utils/itk-wasm-native-get-source.sh, docs/development/hacking_itk_wasm.md
Update documentation and add shell scripts in dev-utils/ folder for cloning source code and building natively.
Add special flags and details for working around MSVC windows quirks.
=> Update docs and add scripts for native build

.github/workflows/cypress.yml
=> ci: disable firefox tests

packages/dicom/python/itkwasm-dicom/README.md, packages/dicom/typescript/README.md
Note:
- C++ libraries that we use
- The libraries' versions
- Funding from IDC
Closes #1206 #1207
=> docs(dicom): add acknowledgments to package documentation

examples/inputs-outputs/package.json, examples/inputs-outputs/typescript/package.json, examples/mean-squares-versor-registration/package.json, examples/mean-squares-versor-registration/typescript/package.json, package.json, packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images-wasi/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-wasi/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/demo-app/package.json, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/test/pipelines/typescript/package.json, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, packages/dicom/python/itkwasm-dicom-wasi/pyproject.toml, packages/dicom/python/itkwasm-dicom/pyproject.toml, packages/downsample/python/itkwasm-downsample-cucim/pyproject.toml, packages/downsample/python/itkwasm-downsample-emscripten/pyproject.toml, packages/downsample/python/itkwasm-downsample-wasi/pyproject.toml, packages/downsample/python/itkwasm-downsample/pyproject.toml, packages/downsample/typescript/package.json, packages/image-io/python/itkwasm-image-io-emscripten/pyproject.toml, packages/image-io/python/itkwasm-image-io-wasi/pyproject.toml, packages/image-io/python/itkwasm-image-io/pyproject.toml, packages/image-io/typescript/package.json, packages/mesh-io/python/itkwasm-mesh-io-emscripten/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io-wasi/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io/pyproject.toml
- build(javascript): remove packageManager specification
- build(python): remove hatch env specifications
=> hatch test deps

include/itkWasmTransformIO.h, packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, packages/mesh-io/typescript/src/mesh-io-index-node.ts, packages/mesh-io/typescript/src/mesh-io-index.ts, packages/mesh-io/typescript/src/write-mesh-node.ts, packages/transform-io/itkInputTransformIO.h, packages/transform-io/typescript/package.json, packages/transform-io/typescript/src/extension-to-transform-io.ts, packages/transform-io/typescript/src/index-common.ts, packages/transform-io/typescript/src/index-node-only.ts, packages/transform-io/typescript/src/mime-to-transform-io.ts, packages/transform-io/typescript/src/read-transform-node.ts, packages/transform-io/typescript/src/read-transform-options.ts, packages/transform-io/typescript/src/transform-io-index-node.ts, packages/transform-io/typescript/src/write-transform-node.ts, packages/transform-io/typescript/src/write-transform-options.ts, packages/transform-io/typescript/test/node/hdf5-test.js, packages/transform-io/typescript/test/node/iwt-test.js, packages/transform-io/typescript/test/node/mat-test.js, packages/transform-io/typescript/test/node/read-transform-node-test.js, packages/transform-io/typescript/test/node/txt-test.js, pnpm-lock.yaml, src/itkWasmTransformIO.cxx
- feat(transform-io): add read-transform-node
- test(transform-io): add read-transform-node-test
- test(node): add format write tests
- feat(transform-io): add writeTransformNode
- feat(itk-wasm-cli): Update default Docker image for 20241111-d4fcf16c
=> transform io high level

packages/core/python/itkwasm/.gitattributes, packages/core/python/itkwasm/.gitignore, packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/itkwasm/transform.py, packages/core/python/itkwasm/pixi.lock, packages/core/python/itkwasm/pyproject.toml, packages/transform-io/pixi.lock, packages/transform-io/pixi.toml
- feat(itkwasm): add Python pixi configuration
- feat(itkwasm): add Python TransformList type
- chore(itkwasm): bump version to 1.0b180
- build(itkwasm): clear dist/ before publish
- build(itkwasm): add more pixi platforms
- build(transform-io): update itkwasm dep to 1.0b180
=> itkwasm pixi

packages/core/typescript/create-itk-wasm/.gitignore, packages/core/typescript/create-itk-wasm/package.json, packages/core/typescript/create-itk-wasm/src/generate/pixi-toml.ts
- chore(create-itk-wasm): bump itkwasm dep to 1.0b185
- chore(create-itk-wasm): bump version to 2.0.0
- build(create-itk-wasm): add native/ to .gitignore
=> create itk wasm bump

.github/workflows/examples.yml, packages/core/typescript/itk-wasm/src/pipeline/internal/load-emscripten-module-main-thread.ts, packages/core/typescript/itk-wasm/src/pipeline/internal/load-emscripten-module-web-worker.ts
- fix(load-emscripten-module-main-thread): load compressed wasm
- ci(examples): retry docker pulls
=> main thread zst

.github/workflows/examples.yml, examples/hello-world/CMakeLists.txt, examples/hello-world/hello.cxx, examples/hello-world/index.html, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/template.package.json, packages/core/typescript/itk-wasm/src/index-worker-embedded.min.ts, packages/core/typescript/itk-wasm/src/version.ts
- build(itk-wasm): use bundled worker for creating bundle
- chore(itk-wasm): bump version to 1.0.0-b.187
- docs(hello-world-example): use itk::wasm::Pipeline
- fix(hello-world-example): update browser use for 1.0.0-b.187
=> itk wasm bundle

packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, src/docker/itk-wasm-base/Dockerfile, src/docker/itk-wasm-base/install-node-js.sh
- build(docker): enable corepack for pnpm availability
- feat(itk-wasm-cli): Update default Docker image for 20250225-5e4b1568
=> docker pnpm

docs/introduction/file_formats/dicom.md, packages/core/typescript/itk-wasm/src/interface-types/poly-data.ts, src/docker/RELEASE.md
- **docs(dicom): note RT Struct support**
- **docs(docker): fix commit message template capitalization**
- **fix(itk-wasm): add metadata to PolyData typescript interface**
=> doc rt struct ts polydata metadata

.github/workflows/scorecard.yml, docs/introduction/parts.md
- docs(parts): add wasmtime-py link
- ci(scorecard): update config for sarif upload error
=> security action

packages/core/typescript/itk-wasm/cypress/e2e/pipeline/pthread-support-available.cy.ts, packages/core/typescript/itk-wasm/src/pipeline/index-common.ts, packages/core/typescript/itk-wasm/src/pipeline/index.ts, packages/core/typescript/itk-wasm/src/pipeline/pthread-support-available.ts, packages/core/typescript/itk-wasm/test/node/pipeline/pthread-support-available-test.js, packages/core/typescript/itk-wasm/test/pipelines/typescript/package.json, packages/core/typescript/itk-wasm/test/pipelines/typescript/vite.config.js, pnpm-lock.yaml
- **feat(itk-wasm): add pthreadSupportAvailable**
- **test(itk-wasm): pthreadSupportAvailable browser test**
- **test(itk-wasm): enable cross origin isolation in browser tests**
=> pthread available
