InsightSoftwareConsortium/ITK-Wasm

package.json
Left over from previous webpack explorations. Can cause dependency resolution
issues like:
$ npm install
[...]
└── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta
|| ^2.2.0-rc but none was installed.
Also update babel-core and babel es2015 preset packages.
=> BUG: Remove babel-loader dependency

circle.yml
Attempt to address "{ ProcessError: ERROR: The key you are authenticating with has been marked as
read only."
=> ci(deploy): set the GIT_PUBLISH_URL in a different way

build.js, package.json
Since these are shipped with browser-based code, they should be small.
Addresses #11
=> feat(build): uglify generated web workers

circle.yml
To address:
All done
npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "/opt/circleci/nodejs/v6.10.3/bin/node" "/opt/circleci/nodejs/v6.10.3/bin/npm" "publish"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
According to: http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules
=> ci(npm): fix authentication with npm.

.circleci/config.yml, package-lock.json, package.json
semantic-release does not understand our setup per
https://maxisam.github.io/2017/03/29/fix-semantic-release-always-push-a-new-major-version/ so it
always bumps the major version.
=> ci(releases): Remove semantic-release automated releases

config/default.js, config/itkConfigBrowserTest.js, karma.conf.js, package-lock.json, package.json, src/itkConfig.js, src/readImageLocalFile.js, src/writeImageLocalFile.js, test/Browser/config/itkConfigBrowserTest.js, test/loadEmscriptenModuleTest.js
Also remove Node.js 'config' support -- in practice, this is not used.
BREAKING CHANGE: Removed 'config' package support.
CC: @agirault
=> chore(browser-testing): Switch to Karma for browser testing

.circleci/config.yml
With workflows, the filters must be in the workflow configuration instead of the job configuration.
=> ci(CircleCI): Specify filters in the workflow configuration

src/Docker/itk-js-vtk/Dockerfile, src/Docker/itk-js/Dockerfile
Also split out itk-js-base (used for building itk.js), and itk-js (used
for projects that use itk-js for their build).
=> feat(Docker): itk-js-vtk Docker image initial addition

README.md, doc/content/api/browser.md, examples/Webpack/src/index.js, src/Docker/itk-js/Dockerfile, src/readImageArrayBuffer.js, src/readImageBlob.js, src/readImageDICOMFileSeries.js, src/readImageFile.js, src/readMeshArrayBuffer.js, src/readMeshBlob.js, src/readMeshFile.js, src/runPipelineBrowser.js, src/writeImageArrayBuffer.js, src/writeMeshArrayBuffer.js, test/Browser/DICOMSeriesTest.js, test/Browser/readImageTest.js, test/Browser/readMeshTest.js, test/Browser/runPipelineBrowserTest.js, test/Browser/writeImageTest.js, test/Browser/writeMeshTest.js
This enables re-use of the web worker or calling `terminate()` on the worker to free resources. We
also fix a bug -- previously only a single worker was being used by the
app.
BREAKING CHANGE: Calls to the browser API must now pass null or a previously generated web worker as
their first argument. The browser API function now return objects with a `webWorker` member.
=> feat(BrowserAPI): Return and accept the web worker used for computation

src/CMakeLists.txt, src/Docker/itk-js-base/Dockerfile, src/Docker/itk-js-vtk/Dockerfile, src/Docker/itk-js/ITKBridgeJavaScript.cmake
@wschroed note, we are updating Emscripten here, which includes [a performance fix for programs with many symbols](https://droettboom.com/blog/2018/04/11/profiling-webassembly/). This may improve the constant overhead we saw in previous VTK WebAssembly experiments.
@jourdain @aylward @floryst this bumps VTK to include *vtkJSONDataSetWriter.cxx*, which will be used for PolyData support.
=> Emscripten bump

src/CMakeLists.txt, src/Docker/itk-js-base/Dockerfile
This is a performance and size optimization for Emscripten. We still enable for the ImageIO's
because it is currently required for the GE formats.
=> perf(Docker): Disable exception catching

.gitignore, build.js, src/Docker/itk-js-vtk/Dockerfile, src/Pipelines/MeshToPolyData/CMakeLists.txt, src/Pipelines/MeshToPolyData/MeshToPolyData.cxx, test/Browser/runPipelineBrowserTest.js, test/runPipelineNodeSyncTest.js, test/runPipelineNodeTest.js
Convert a itk.js Mesh JavaScript object to a vtk.js PolyData JavaScript
Object.
This is a standard pipeline to be distributed with the itk.js npm
package.
=> feat(Pipelines): Add MeshToPolyData

build.js
/ITK-build gets converted to C:/Program Files/Git/ITK-build ...
=> build(build.js): Fix dockcross invocation with MSYS

src/CMakeLists.txt
These are currently the only ones that need it.
=> build(ImageIOs): Only enable exception catching on GE modules

.circleci/config.yml
CircleCI now refuses to build open source projects when this is enabled.
=> ci(Circle): Remove docker_layer_caching

src/itk-js-cli.js
Currently when "npx itk-js build ." is called on windows, itk-js-cli.js attempts to call web-build/itk-js-build-env using cmd. This commit modifies its behavior to use git bash instead. It also adds some logging so that if spawnSync fails, a helpful error message is printed instead of failing silently.
=> Modify itk-js-cli.js to call git bash on windows

.circleci/config.yml
According to the 2.0 documentation:
https://circleci.com/docs/2.0/configuration-reference/#branches
=> ci(Circle): Remove 'filters' from gh-pages branch ignore

karma.conf.js, src/WorkerPool.js
Re-use the last-used worker. This results in a preference for a spawned
worker and compiled wasm over replacing a `null` queue entry.
=> perf(WorkerPool): Prefer most-recently-used worker

src/MimeToImageIO.js, src/extensionToImageIO.js, test/MimeToImageIOTest.js, test/extensionToImageIOTest.js
GDCM supports more transfer syntaxes.
=> fix(readImageFile): Default to GDCM for DICOM files

src/EmscriptenModule/itkJSPost.js, src/WebWorkers/ImageIO.worker.js, src/WebWorkers/MeshIO.worker.js
WORKERFS Blob mounting turns out to have a gigantic, i.e. 10X in GDCM
DICOM series reading, performance penalty.
=> perf(IO): Use MEMFS over WORKERFS

examples/UnpkgIO/src/index.js, examples/Webpack/src/index.js, src/WorkerPool.js, test/Browser/WebWorkerPoolTest.js
BREAKING_CHANGE: WorkerPool's optional progressCallback is passed to runTasks instead of the constructor
=> feat(WorkerPool): Support parallel calls to runTasks

src/WorkerPool.js
With many tasks, this can result in resolving prematurely.
=> fix(WorkerPool): Do not postpone multiple times

.circleci/config.yml
The Unpkg.io can be slow to wake up, causing false positives.
=> ci(Circle): Do not run UMD tests

src/WorkerPool.js
When runTasks is called many times repeatedly with small tasks, the
worker can be surrendered and not used for the next task -- the Promise
will never resolve.
=> fix(WorkerPool): Resolve with many task sets

src/Docker/itk-js-base/Dockerfile
This should fix https://github.com/Kitware/paraview-glance/issues/367.
Issue: openjp2 expects threads to be on by default, so it hangs while waiting for threads to initialize (which they never will, presently). This affects loading jpeg2000 images.
The `OPJ_USE_THREAD:BOOL=OFF` flag didn't work for me initially, so I change the openjp2 CMake file to turn off the threads option. Is there a better way of ensuring the option gets applied to gdcm's openjp2 lib? I can try again with just the flag (and without the sed hackery).
=> Disable threads for openjp2

examples/Node.js/package.json
The error now contains a traceback that starts with `Error: Could not
find IO for: [...]`
=> fix(Node.jsExample): Correct error with unknown file type write attempt

src/WebWorkers/Pipeline.worker.js, src/WorkerPool.js, src/readImageDICOMFileSeries.js, test/Browser/WebWorkerPoolTest.js
This PR changes the behavior of the `WorkerPool.runTasks` method so instead of returning a promise, it returns an object containing the original promise along with an id that can be used to cancel pending tasks before they have been executed by a worker (cancelation is achieved via a new `cancel(runId)` method added to the `WorkerPool` api).
=> Support cancel pending tasks which have not yet run

doc/content/api/browser_io.md, doc/content/api/node_io.md, src/Bindings/itkDICOMTagReaderJSBinding.cxx, src/CMakeLists.txt, src/WebWorkers/ImageIO.worker.js, src/readDICOMTags.js, src/readDICOMTagsEmscriptenFSFile.js, src/readDICOMTagsLocalFile.js, src/readDICOMTagsLocalFileSync.js, test/Browser/DICOMTest.js, test/DICOMTest.js
This adds an API for reading DICOM tags from DICOM object files. Additionally, appropriate character set conversion is performed, decoding encoded strings into UTF-8.
Relevant issue: #394 
Todo:
=> Read dicom tags

.github/workflows/release-notes.yml
We need all commits and tags from the full history.
=> ci(ReleaseNotes): Set checkout fetch-depth to 0

include/itkWASMExports.h, src/docker/itk-wasm/ITKWebAssemblyInterface.cmake
Avoid missing symbols when an executable does not link to the
WebAssemblyInterface library.
=> build(Emscripten): Use EMSCRIPTEN_KEEPALIVE over EXPORTED_FUNCTIONS

src/io/readDICOMTags.ts
Importing from '../index.js' pulls in node imports, which is not
desirable for web-based distribution. Instead of importing from index, import directly from InterfaceTypes.
Fixes #470.
=> fix(readDICOMTags): import InterfaceTypes directly

src/itk-wasm-cli.js
Otherwise we can end up with `//` in the path, which causes issues down
the line.
=> fix(itk-wasm-cli.js): Use path.join to construct dockcrossScript

src/web-workers/pipeline.worker.ts
this unnecessary adds logging to the console and slows down the process when the dev tools are open
=> fix: remove console.log from pipeline worker

src/core/WorkerPool.ts
On Chrome repeated calls to the worker pool can accumulate leaks due to
reject / resolve holding a reference to results even after the
associated Promise has resolved.
Co-authored-by: Forrest Li <forrest.li@kitware.com>
Co-authored-by: Will McCambley <willmccambley@gmail.com>
Co-authored-by: Sankhesh Jhaveri <sankhesh.jhaveri@kitware.com>
=> fix(WorkerPool): Address memory leak in Chrome from reject/resolve

src/io/internal/bindings/image-io.package.json.in, src/io/internal/bindings/mesh-io.package.json.in
These are optional dependencies for itk-wasm. Avoid pulling down
node_modules/itk-image-io/node_modules/itk-wasm/*
=> build(io-packages): Remove dependency on itk-wasm

doc/content/docs/itk_js_to_itk_wasm_migration_guide.md, src/io/writeArrayBuffer.ts, src/io/writeImageArrayBuffer.ts, src/io/writeImageLocalFile.ts, src/io/writeLocalFile.ts, src/io/writeMeshArrayBuffer.ts, src/io/writeMeshLocalFile.ts, test/browser/io/writeImageTest.js, test/browser/io/writeMeshTest.js, test/node/io/image/BYUTest.js, test/node/io/image/BioRadTest.js, test/node/io/image/MGHTest.js, test/node/io/image/MetaImageTest.js, test/node/io/image/NRRDTest.js, test/node/io/image/NiftiTest.js, test/node/io/image/PNGTest.js, test/node/io/image/TIFFTest.js, test/node/io/image/VTKTest.js, test/node/io/image/WASMTest.js, test/node/io/image/writeImageLocalFileTest.js, test/node/io/mesh/FreeSurferTest.js, test/node/io/mesh/GIPLTest.js, test/node/io/mesh/OBJTest.js, test/node/io/mesh/OFFTest.js, test/node/io/mesh/STLTest.js, test/node/io/mesh/writeMeshLocalFileTest.js
BREAKING_CHANGE: The `useCompression` argument now comes last in the functions that write images and meshes to array buffers and files
=> refactor(writeImage,Mesh): useCompression argument comes last

examples/UMD/cypress/integration/load_data_spec.js, src/build-emscripten.js, src/core/internal/loadEmscriptenModuleWebWorker.ts, src/io/internal/pipelines/image/ReadDICOM/CMakeLists.txt
The *.umd.wasm files are identical to the *.wasm files. Have the .umd.js
bindings use the *.wasm WebAssembly files. This cuts the package size
roughly in half to keep us under the 100 MB jsDelivr limit.
=> fix(jsDelivr): Remove *.umd.wasm files from package

src/io/internal/pipelines/image/ReadDICOM/ReadImageDICOMFileSeries.cxx
Even though UseSeriesDetails was set to true, the default restrictions were missing.
These restrictions are used to sub-refine the DICOM file set into different series.
=> improvement(DICOM IO): Add default restrictions to DICOM reader

doc/content/docs/itk_js_to_itk_wasm_migration_guide.md, src/core/internal/createWebWorkerPromise.ts, src/io/internal/pipelines/image/ConvertImage/CMakeLists.txt, src/io/internal/pipelines/mesh/ConvertMesh/CMakeLists.txt, src/io/meshToPolyData.ts, src/io/polyDataToMesh.ts, src/io/readDICOMTagsArrayBuffer.ts, src/io/readImageArrayBuffer.ts, src/io/readImageDICOMArrayBufferSeries.ts, src/io/readMeshArrayBuffer.ts, src/io/writeImageArrayBuffer.ts, src/io/writeMeshArrayBuffer.ts, src/itkConfig.ts, src/itkConfigCDN.js, src/pipeline/runPipeline.ts, src/web-workers/ITKConfig.ts, test/browser/config/itkConfigBrowserTest.js
- refactor(createWebWorkerPromise): Remove name argument
- build(Convert{Image,Mesh}): Update factory register manager CMake variables
- refactor(createWebWorkerPromise): Use pipelineWorkerUrl with full path to worker
=> pipeline full path

CMakeLists.txt
Address:
Make Error in /home/matt/bin/ITK2-GCC-Release/_deps/libcbor-src/src/CMakeLists.txt:
Target "cbor" INTERFACE_INCLUDE_DIRECTORIES property contains path:
"/home/matt/bin/ITK2-GCC-Release/_deps/libcbor-src/src"
which is prefixed in the build directory.
=> build(libcbor): Remove target_include_directories with build tree

package-lock.json, package.json, src/docker/itk-wasm-base/Dockerfile, src/itk-wasm-cli.js, src/itkConfig.ts, src/web-workers/loadImageIOPipelineModule.ts, src/web-workers/loadMeshIOPipelineModule.ts, test/browser/io/readImageTest.js
- feat(Docker): Update WASI, Emscripten toolchains for LLVM 14
- feat(itk-wasm-cli): Update default Docker image for LLVM 14
- feat(version): Bump version to 1.0.0-b.15
=> toolchain bumps

src/core/Image.ts, src/io/internal/pipelines/image/ReadDICOM/ReadImageDICOMFileSeries.cxx, src/io/readImageDICOMArrayBufferSeries.ts, src/io/readImageDICOMFileSeries.ts
This is to redo PR https://github.com/InsightSoftwareConsortium/itk-wasm/pull/584 with proper commit message format.
The functions readImageDICOMFileSeries and readImageDICOMArrayBufferSeries
have an additional side effect that it sorts / orders the files
(particularly DICOM files) based on a pre-defined logic in gdcm.
However, this information is not related to the caller in any form.
Add Array<string> as the ordered list of filenames as additional output.
=> feat(ReadImageDICOM): Return sorted file list when reading DICOM series

src/docker/itk-wasm-base/Dockerfile
Requires the latest Docker Desktop. A few warnings about the
architectures may still be present.
=> build(Docker): update dockcross for Apple Silicon builds

package.json
This allows for a subject line to start with an upper case.
=> chore(commitlint): allow upper-case subject

CMake/ITKExternalData.cmake
Steps:
1. Rsync updates to the DataLad repository
cd ~/data/itk-wasm-testing-data
rsync -rvt ~/src/itk-wasm/build-emscripten/ExternalData/ ./
datalad save
datalad push --to github
2. Export for upload to IPFS
datalad export-archive /tmp/itk-wasm-testing-data.tar.gz
cd /tmp
tar xvzf itk-wasm-testing-data.tar.gz
cd itk-wasm-testing-data
w3 put . -n itk-wasm-testing-data-v1.0.0-b.18 -H --no-wrap
3. Pin the CID on Pinata
4. Pin the CID on estuary.tech
=> ci(TestingData): Update IPFS configuration

src/core/internal/createWebWorkerPromise.ts
When running task in a worker in "parallel" the access to the worker must be performed through the same worker promise otherwise requests and responses can get interleaved. This situation can occur if for example `Promise.all(...)` is used to run the tasks in the worker. To prevent this issue we attach the work promise to the worker, so it can be used again if the worker is reused.
=> fix(worker): Ensure worker promises are reused

src/docker/itk-wasm-base/Dockerfile
This is an first attempt to build and link DCMTK in web-assembly with itk-wasm. It is needed for supporting structured reports, particularly SoP classes (88.11, 88.22, and 88.33). In the next iterations it will be expanded to support Encapsulated PDFs (104.1) and X-Ray Dose report (88.67).
Updated Dockerfile to enable DCMTK building with ITK. When enabling DCMTK in ITK-C++ and building using WASI and Emscripten, many compiler errors were encountered. The associated fixes for these compiler errors reside in the following branches:
ITK
https://github.com/jadh4v/ITK/commits/ITKWASM-2022-07-02-5e7aea9
DCMTK
https://github.com/jadh4v/DCMTK/commits/20220802_DCMTK_PATCHES_FOR_ITK-wasm
=> Build DCMTK with ITK for supporting structured reports

package.json
GitHub primarily supports the https protocol.
=> ci(repository-url): Remove git+ protocol prefix

package.json
https://nodejs.org/api/packages.html#conditional-exports
> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last.
=> build(ExportMap): Add "default" entry

src/itk-wasm-cli.js
More consistency with WASM community tooling.
=> refactor(itk-wasm-cli): Rename bindings subcommand to bindgen

src/core/index.ts, src/itkConfig.ts, update-versions.cjs
The idea is to be able to do `import { version } from 'itk-wasm'` as it can be useful to know the version to use it in the build process to version the assets and invalidate caches.
=> feat: expose version

.gitignore, dist/dicom/src/StructuredReportToHtmlNodeResult.ts, dist/dicom/src/StructuredReportToHtmlOptions.ts, dist/dicom/src/StructuredReportToHtmlResult.ts, dist/dicom/src/index.ts, dist/dicom/src/indexNode.ts, dist/dicom/src/structuredReportToHtml.ts, dist/dicom/src/structuredReportToHtmlNode.ts, dist/dicom/test/node.js, src/core/internal/camelCase.ts, src/io/internal/pipelines/dicom/CMakeLists.txt, src/io/internal/pipelines/dicom/structured-report-to-html.cxx, src/itk-wasm-cli.js
Add capability to read and render a dicom file structured report into an html document using implementation from DCMTK's `dsr2html` command line app.
=> Feature: add structured-report-to-html operation

src/core/index.ts, src/core/internal/camelCase.ts, test/Input/104.1-SR-printed-to-pdf.dcm.cid, test/Input/88.67-radiation-dose-SR.dcm.cid
By default web3.storage provides CID value that points to a wrapped
parent folder. This leads to corrupt file download.
Fix is to extract the correct file-level CID from the download URL.
For more details see:
https://web3.storage/docs/how-tos/troubleshooting/#the-cid-returned-when-uploading-doesnt-link-directly-to-my-file
Additional updates regarding style fixes by linter.
=> fix(SR-test-data): switch to file-level CID values

src/itkConfig.ts
Otherwise, this ends up loading './index.js', which brings in Node.js, which causes issues for Vite / Rollup when bundling for the browser.
Closes #654
=> fix(itkConfig.ts): Import from './browser/index.js'

dist/dicom/src/StructuredReportToHtmlOptions.ts, dist/dicom/src/readDicomEncapsulatedPdf.ts, dist/dicom/src/readDicomEncapsulatedPdfNode.ts, dist/dicom/src/structuredReportToHtml.ts, dist/dicom/src/structuredReportToHtmlNode.ts, dist/dicom/src/structuredReportToText.ts, dist/dicom/src/structuredReportToTextNode.ts, dist/dicom/test/node.js, src/docker/itk-wasm-base/Dockerfile, src/io/internal/pipelines/dicom/structured-report-to-html.cxx, src/itk-wasm-cli.js, test/CMakeLists.txt, test/Input/88.59-KeyObjectSelection-SR.dcm.cid, test/Input/test-style.css.cid
Key object selection (KOS) structured report (SR) is similar to any other type of structured reports like radiation dose or comprehensive SR, except that a KOS has a list of referenced composite objects (images, waveforms, etc). These references are presented as a list of hyperlinks to the DICOM database files.
DCMTK renders these hyperlinks using a fixed literal ` http://localhost/dicom.cgi ` which is hard coded through a:
```c++
#define HTML_HYPERLINK_PREFIX_FOR_CGI
```
We replace this with a passed string argument to allow flexible hyperlinks based on the requirements of the calling application.
=> feat(key-object-selection): support for rendering key object selection structured report

package.json
According to:
https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md
The npm tarball is generated by the @semantic-release/npm plugin during the `prepare` step. So, bump the update version script execution to the `verifyReleaseCmd`.
=> ci(update-versions): Run during verifyReleaseCmd

package.json, src/core/index.ts, src/itkConfigDevelopment.ts, src/update-versions.cjs
Get the version from package.json, which should be set by semantic-release.
=> fix: Run update-versions during prepublishOnly npm step

package.json
The dependency on itk-wasm was `itk-wasm@0.0.0-semantically-released` following #668
=> fix(io-packages): Update with main package semantic-release version

CMake/ITKExternalData.cmake
Also try estuary.tech before another web3.storage attempt.
=> test: Retrieve released data from Kitware's Apache server

src/core/createWebWorkerPromise.ts, src/io/meshToPolyData.ts, src/io/polyDataToMesh.ts, src/io/readDICOMTagsArrayBuffer.ts, src/io/readImageArrayBuffer.ts, src/io/readImageDICOMArrayBufferSeries.ts, src/io/readMeshArrayBuffer.ts, src/io/writeImageArrayBuffer.ts, src/io/writeMeshArrayBuffer.ts, src/pipeline/runPipeline.ts
This results in:
-    worker = new Worker(new URL('../../web-workers/pipeline.worker.js', import.meta.url))
+    worker = new Worker(new URL('../web-workers/pipeline.worker.js', import.meta.url))
which helps the use case:
1) bundle with rollup
2) bundle the resulting bundle with vite
=> fix(createWebWorkerPromise): Move up one directory

cypress/e2e/pipeline/runPipeline.cy.ts, src/core/createWebWorkerPromise.ts, src/pipeline/runPipeline.ts
Use case: set to null so vite / webworker vendor.
=> feat(runPipeline): Support specification of pipelineWorkerUrl

.github/workflows/cxx-python.yml
Brings in https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/54 to work around sprintf errors.
=> ci(MacOSCxx): Bump Action to use XCode 13.2

package.json, packages/compress-stringify/typescript/package.json, packages/compress-stringify/typescript/pnpm-lock.yaml, packages/compress-stringify/typescript/src/pipeline-worker-url.ts, packages/compress-stringify/typescript/src/pipelines-base-url.ts, packages/compress-stringify/typescript/test/browser/app.ts, src/bindgen/typescript-resources/pipeline-worker-url.ts, src/bindgen/typescript-resources/pipelines-base-url.ts, src/bindgen/typescript-resources/template.package.json, tsconfig.json
At runtime, we use in order of preference:
1. Package asset configuration
2. itk-wasm asset configuration
3. jsDeliver
=> feat(bindgen): Default to itk-wasm package asset configuration

cypress/e2e/pipeline/runPipeline.cy.ts, src/bindgen/typescript.js, src/browser/index.ts, src/pipeline/RunPipelineOptions.ts, src/pipeline/runPipeline.ts
Order independent and allow for future options, e.g. disableSimd.
=> refactor(runPipeline): Pass execution options in options object

examples/debugging/package.json
To address:
```
> itk-wasm-debugging-example@1.0.1 wasi-build-debug /home/local/KHQ/will.schroeder/Develop/wasm/itk-wasm/examples/debugging
> itk-wasm -i itkwasm/wasi --build-dir wasi-build-debug build -- -DCMAKE_BUILD_TYPE=Debug
/home/local/KHQ/will.schroeder/Develop/wasm/itk-wasm/examples/debugging/node_modules/itk-wasm/src/itk-wasm-cli.js:3
import fs from 'fs-extra'
```
=> fix(DebuggingExample): Bump itk-wasm version for missing fs-extra dep

docs/tutorial/hello_world.md
Fixes the default build directory for wasi.
=> docs(HelloWorld): Update itk-wasm version to 1.0.0-b83

src/docker/itk-wasm-base/wasmtime-pwd.sh, src/itk-wasm-cli.js
Enables running ctest from a subdirectory of the build tree.
Also improve flag documentation.
Remove unused wasmtime-pwd.sh
This is in the dockcross image.
=> feat(CLI): Add --test-dir option to test subcommand

src/bindgen/python.js, src/bindgen/typescript-resources/pipelines-base-url.ts, src/bindgen/typescript.js, src/itk-wasm-cli.js
- Support unsigned integer as pipeline parameter.  
- Only generate bindgen for specified language.
- Default CDN url uses package name.
=> Bindgen patches

src/core/internal/loadEmscriptenModuleNode.ts
Required for loading a module on Windows in Node 18.
=> fix: Use pathToFileURL for loading js module on Windows

package.json
Allows Typescript project to use `nodenext` module resolution strategy.
```json
"compilerOptions": {
"moduleResolution": "nodenext"
}
```
More info:
https://moonrepo.dev/docs/guides/javascript/typescript-project-refs#enabling-importsexports-resolution
and of course:
https://nodejs.org/api/packages.html#community-conditions-definitions
=> fix(package): add types entry to exports

src/bindgen/python-resources/template.pyproject.toml
Home is expected to be replaced by the built project documentation after it has been published.
=> feat(bindgen): Add pyproject.toml project.urls

package-lock.json, package.json
Might help  downstream bundling with Vite 3.0.  `axios` 1.* publishes ESM modules.
=> chore(package): bump axios from 0.23.0 to 1.4.0

src/bindgen/typescript-resources/template.package.json
To address:
[!] RollupError: "TextEncoder" is not exported by "polyfill-node.util.js", imported by "node_modules/axios/lib/helpers/formDataToStream.js". 64
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module 65
node_modules/axios/lib/helpers/formDataToStream.js (1:8) 66
1: import {TextEncoder} from 'util';
67
^
=> fix(bindgen): Bump typescript package deps

examples/mean-squares-versor-registration/package.json
Addresses:
```
[!] RollupError: "TextEncoder" is not exported by "polyfill-node.util.js",
imported by "node_modules/axios/lib/helpers/formDataToStream.js".
64
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
65
node_modules/axios/lib/helpers/formDataToStream.js (1:8)
66
1: import {TextEncoder} from 'util';
67
^
```
=> build(mean-squares-version-registration): Bump itk-wasm to 1.0.0-b.114

package.json, packages/dicom/typescript/test/node.js
Total DICOM SOP test cases (including previously existing tests):
Non-Image SOPs:
✔ read Radiation Dose SR (477ms)
✔ Apply presentation state to dicom image. (521ms)
✔ read Key Object Selection SR (558ms)
✔ structuredReportToText (593ms)
✔ readDicomEncapsulatedPdfNode (604ms)
✔ structuredReportToHtml (658ms)
✔ Apply color presentation state (CSPS) to a color dicom image. (1.9s)
Image SOPs:
✔ DICOM SOP: Segmentation Storage. (1.6s)
✔ DICOM SOP: Secondary Image Storage. (1.6s)
✔ DICOM SOP: RT Dose Storage. (1.6s)
✔ DICOM SOP: Digital Mammography X-Ray Image Storage. (1.8s)
✔ DICOM SOP: Digital X-Ray Image. (1.9s)
✔ DICOM SOP: CT Image. (1.9s)
✔ DICOM SOP: Ultrasound Multi-frame Image Storage. (2s)
✔ DICOM SOP: Positron Emission Tomography Image Storage. (2.3s)
✔ DICOM SOP: MR Image. (2.3s) …
=> test(dicom): test multiple SOP classes

packages/dicom/typescript/package.json
Update export location to match package installation.
Fix for error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
'...node_modules\@itk-wasm\dicom\dist\bundles\dicom.node.js'
imported from ...
```
=> fix(dicom-node): export location

packages/dicom/typescript/src/read-image-dicom-file-series.ts, src/bindgen/typescript/function-module.js
An await is required if File objects are passed to `readImageDicomFileSeries()`. This is not caught in current cypress tests, since the test calls `readImageDicomFileSeries` with ArrayBuffer objects which doesn't require await since already in memory).
Error details:
```
CLI::ArgumentMismatch: --input-images: 1 required INPUT_BINARY_FILE:FILE missing
```
This fix is related to the following PR for VolView:
https://github.com/Kitware/VolView/pull/385
see: https://github.com/Kitware/VolView/pull/385#discussion_r1286418006
=> fix(readImageDicomFileSeries): await if file objects are passed

packages/dicom/typescript/src/read-dicom-tags-options.ts, packages/dicom/typescript/src/read-dicom-tags-result.ts
=> fix(read-dicom-tags): tweek typescript options and return types

.github/workflows/examples.yml, .github/workflows/javascript-typescript.yml, .github/workflows/pr-checks.yml, .github/workflows/toolchains.yml, .github/workflows/wasi.yml
Fix GitHub actions workflow warnings linked to `Node.js`: bump `actions/checkout` and `actions/setup-node` to `v3`.
Fixes:
```
The following actions uses node12 which is deprecated and will be forced to run on node16:
actions/checkout@v2, actions/setup-node@v2.
For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
raised for example in:
https://github.com/InsightSoftwareConsortium/itk-wasm/actions/runs/5943988559
=> ci(actions): Fix GitHub actions workflow warnings linked to `Node.js`

packages/compare-images/typescript/package.json, packages/compress-stringify/typescript/package.json, packages/dicom/typescript/package.json, src/bindgen/typescript/resources/template.package.json
"types" outside exports is listed as a "fallback" per
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
=> build: add typescript types to "exports" in package.json

packages/dicom/typescript/package.json
The output file is `dicom-node.js` instead of `dicom.node.js`.
=> fix(dicom): typo in node export

.github/workflows/examples.yml, .github/workflows/pr-checks.yml, .github/workflows/wasi.yml
Make Node.js versions consistent across workflow file jobs: use version 18.
=> ci: make node.js versions consistent across workflow file jobs

CMakeLists.txt
Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE`: the timestamps of the extracted files will reflect the timestamps in the archive.
Fixes:
```
CMake Warning (dev) at D:/a/_temp/-2103337693/cmake-3.24.2-windows-x86_64/share/cmake-3.24/Modules/ExternalProject.cmake:3074 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP …
```
=> build(cmake): set `download_extract_timestamp` to `true`

CONTRIBUTING.md
Add contributing documentation file: cross-reference the contributing
section of the `hacking_itk_wasm.md` file.
=> docs: add contributing documentation file

CMakeLists.txt
Set the `CMP0135` CMake policy to `NEW`: the timestamps of the extracted files will reflect the timestamps at extraction.
Setting the `download_extract_timestamp` to `true` (commit 5ca66d6) did not fix the warning.
=> build(cmake): set `cmp0135` cmake policy to `new`

src/bindgen/typescript/function-module.js
In the browser, they are not mounted. Follow-up to 3ff0d7385b3812f72b03720dc2a4dd32e5835bc4.
=> fix(bindgen): only skip output index for files with node

.github/workflows/cypress.yml, .github/workflows/examples.yml, .github/workflows/javascript-typescript.yml, .github/workflows/pr-checks.yml, .github/workflows/toolchains.yml, .github/workflows/wasi.yml
- ci: make ubuntu versions consistent across workflow file jobs
- ci: use GitHub Action to free up disk space
=> ci: make ubuntu versions consistent across workflow file jobs

src/core/createWebWorkerPromise.ts
creation
Follow-up to #970 when using Vite with derived packages.
=> fix(createWebWorkerPromise): use type: 'module' option for Worker

src/core/createWebWorkerPromise.ts
Addresses:
blob:http://localhost:5173/e8a4572c-e8e3-4174-916d-f90930010413	(failed)net::ERR_FILE_NOT_FOUND	script	Other
with local development of derived apps.
=> fix(createWebWorkerPromise): revoke revokeObjectURL

docs/introduction/file_formats/images.md
Honor the `NIfTI` format case in the supported file format list.
=> docs: honor nifti case in supported image file format list

packages/core/typescript/itk-wasm/cypress/e2e/pipeline/run-pipeline.cy.ts, packages/core/typescript/itk-wasm/src/pipeline/create-web-worker.ts, packages/core/typescript/itk-wasm/src/pipeline/create-worker-proxy.ts, packages/core/typescript/itk-wasm/src/pipeline/index.ts
So compatible web workers can be created explicitly when desired.
=> feat: provide createWebWorker

packages/core/typescript/itk-wasm/src/cli/pnpm-script.js
Fixes a typo in the default docker image name of `itk-wasm pnpm-scripts` cli.
Fixes #1059
=> fix: fix docker image name in pnpm-scripts cli

packages/core/typescript/itk-wasm/src/bindgen/python/wasi/wasi-function-module.js
Getting runtime type error in `path` with 
```
for value in files:
input_file = str(PurePosixPath(files))
``` 
Changes to 
```
for value in files:
input_file = str(PurePosixPath(value))
```
=> fix(wasi-function-module): use file path variable name

packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/test/pipelines/typescript/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
lstat not found errors from npm.
=> test(itk-wasm): avoid use of npm link in bindgen test for Windows

packages/core/typescript/itk-wasm/src/pipeline/create-web-worker.ts
Calling `createWebWorker()` with an undefined `pipelineWorkerUrl` should be equivalent to passing in `null`.
=> fix(create-web-worker): allow undefined workerUrl

packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, src/docker/RELEASE.md, src/docker/itk-wasm-base/Dockerfile
- chore(docker): bump Node version to 20.12.2
- feat(itk-wasm-cli): Update default Docker image for 20240415-8c69d3f8
- docs(docker): document build, test as part of the image release process
=> docker image bump

packages/compare-meshes/typescript/package.json, packages/downsample/typescript/test/browser/demo-app/index.html, pnpm-lock.yaml
- chore: update downsample demo-app index.html
- build(compare-meshes): update @itk-wasm/app dep
=> compares meshes demo

packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/template.package.json
This is likely to get out-of-sync and conflict with the itk-wasm build
scripts package.json packageManager pnpm version.
=> fix(bindgen): remove packageManager version from template.package.json

packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, src/docker/itk-wasm-base/Dockerfile
- build(docker): bump ITK to v5.4.0
- feat(itk-wasm-cli): Update default Docker image for 20240521-17db8b0b
=> itk 5.4.0 docker

packages/core/typescript/create-itk-wasm/package.json, packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/create-itk-wasm/src/generate/pipeline.ts, packages/core/typescript/create-itk-wasm/src/inquire/edit-wanted-machine.ts, packages/core/typescript/create-itk-wasm/src/inquire/project-spec.ts
- chore(create-itk-wasm): bump itk-wasm version to 1.0.0-b.175
- style(create-itk-wasm): obtainedReponse -> obtainedResponse
- fix(create-itk-wasm): input project description must not be empty
- fix(create-itk-wasm): support dispatch on parameters
=> create itk wasm tweaks

packages/image-io/typescript/src/image-io-index.ts
Fix https://github.com/InsightSoftwareConsortium/itk-wasm/issues/1141 by renaming MINC ImageIO from `minc` to `mnc` to be consistent with `extension-to-image-io.js`
=> Fix https://github.com/InsightSoftwareConsortium/itk-wasm/issues/1141

CMakeLists.txt
- **chore: bump cli11 to v2.4.2**
- **build: bump rang cmake_minimum_required to 3.16.3**
=> cli11 rang bump

docs/cxx/interface_types.md, include/itkInputTransform.h, include/itkOutputTransform.h, include/itkTransformJSON.h, include/itkTransformToWasmTransformFilter.h, include/itkTransformToWasmTransformFilter.hxx, include/itkWasmTransform.h, include/itkWasmTransform.hxx, include/itkWasmTransformIO.h, include/itkWasmTransformToTransformFilter.h, include/itkWasmTransformToTransformFilter.hxx, include/itktransformParameterizationString.h, model/itk-wasm.yml, src/CMakeLists.txt, src/itkWasmTransformIO.cxx, src/itktransformParameterizationString.cxx, test/CMakeLists.txt, test/itkPipelineMemoryIOTest.cxx, test/itkPipelineTest.cxx, test/itkWasmTransformInterfaceCompositeTest.cxx, test/itkWasmTransformInterfaceTest.cxx
- docs: add TransformList, Transform LinkML model
- refactor: remove old module IO CMake code
- feat: add itk::WasmTransformIOFactory
- feat: itk::WasmTransformIO initial addition
- feat(WasmTransformIO): support Composite transforms
- ci: Do not build macos-12 in CI
- feat(TransformJSON): specify initializers
- fix: use initialization with braces in itkTransformJSONTest
- feat: bump glaze to 2.9.3
- build: use XCode 15.3 for std::hash<std::filesystem::path>
- build: add itkFloatTypesJSON.h to KWStyle namespace disable
- build: do not build manylinux2014 native binary wheels
- build(glaze): add flags required for MSVC
- build: check the result of glz::write in itkWasmTransformIO
- ci: disable native python build workflow
- feat: wasm transform interface classes
=> transform interface

CMakeLists.txt, src/itkPipeline.cxx
Fix a bug where a call to --help and printing of parameters for
a cli app would crash if a description or parameter line
did not contain any space.
ITK-Wasm prefers static build. For native build on windows (msvc),
it is necessary to enable/specify the use of static runtime debug
library indicated by the /MTd compiler flag.
Add a CMAKE flag (default: ON) to enable/disable this compiler
flag when msvc is being used for building.
=> Fix itkPipeline help stream parsing crash and native msvc static debug build

include/itkOutputImage.h, packages/core/typescript/itk-wasm/src/cli/default-image-tag.js
As a follow-up to f9f2805766ae1da281dc35dc6c1b3405911007f3, we still
need the component per pixel when computing the data size.
=> fix(OutputImage): dataSize needs components per pixel

docs/conf.py
Specify the Read The Docs custom domain in the documentation config file.
Read the Docs is deprecating Sphinx context injection at build time starting Monday, Oct 7, 2024, so any custom domain specified in the Read the Docs admin needs to be defined in the configuration file.
Documentation:
https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> STYLE: Specify ReadTheDocs custom domain name

packages/core/typescript/itk-wasm/src/cli/pnpm-script.js
Prefix docker image names with registry paths so that they work with `podman` without setting local environment for unqualified-search-registries.
=> Add quay prefix to docker image names

packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/index-worker-embedded.ts
Avoid implicit `any`. `string` may not be technically right -- this
`.worker.js` is a worker module source treated specially by bundlers.
=> build(index-worker-embedded): specify pipelineWorker type

docs/development/itk_js_to_itk_wasm_migration_guide.md, packages/core/typescript/itk-wasm/src/deprecated/read-image-array-buffer.ts, packages/core/typescript/itk-wasm/src/deprecated/read-image-blob.ts, packages/core/typescript/itk-wasm/src/deprecated/read-image-file.ts, packages/core/typescript/itk-wasm/src/deprecated/read-image-local-file.ts, packages/core/typescript/itk-wasm/src/deprecated/read-mesh-array-buffer.ts, packages/core/typescript/itk-wasm/src/deprecated/read-mesh-blob.ts, packages/core/typescript/itk-wasm/src/deprecated/read-mesh-file.ts, packages/core/typescript/itk-wasm/src/deprecated/read-mesh-local-file.ts, packages/core/typescript/itk-wasm/src/deprecated/write-image-array-buffer.ts, packages/core/typescript/itk-wasm/src/deprecated/write-image-local-file.ts, packages/core/typescript/itk-wasm/src/deprecated/write-mesh-array-buffer.ts, packages/core/typescript/itk-wasm/src/deprecated/write-mesh-local-file.ts
- docs(image-io): correct new names for deprecated functions
- docs(mesh-io): correct new names for deprecated functions
=> read function names

packages/dicom/dcmtk/CMakeLists.txt
Move to upstream and remove trailing `.git` who use is deprecated.
Closes #1202 #1203
=> build(dicom): using QIICR dcmqi 2024-08-28 master

packages/core/typescript/demo-app/package.json, packages/downsample/typescript/test/browser/demo-app/downsample-bin-shrink-load-sample-inputs.ts, packages/downsample/typescript/test/browser/demo-app/downsample-label-image-load-sample-inputs.ts, packages/downsample/typescript/test/browser/demo-app/downsample-load-sample-inputs.ts, pnpm-lock.yaml
- **chore(demo-app): bump dependency versions**
- **fix(downsample): load sample input image into viewer in demo app**
=> demo app viewer version

packages/dicom/python/itkwasm-dicom/docs/acknowledgments.md, packages/dicom/python/itkwasm-dicom/docs/index.md
=> docs: add Acknowledgments to Python online docs

.github/workflows/native.yml
To address:
> Error
> the `uses' attribute must be a path, a Docker image, or owner/repo@ref
=> ci(native): add ref to setup-pixi

docs/python/itk_python.md
Also simplify the native example so it is easy to see the
correspondance.
=> docs(itk-python): example of file format conversion via wasm io packages

.github/workflows/python-wasm.yml
=> ci(python-wasm): fix pyodide install-browser version

include/itkWasmImageToImageFilter.hxx
Hi,
This PR fixes an issue in which a segfault could occur when calculating the total size of the buffered region. If my understanding is correct here, `imageJSON.size[i]` should be used if `imageJSON.bufferedRegion.size` is undefined.
Related thread on the ITK forum: https://discourse.itk.org/t/running-pipeline-inputs-outputs-tutorial-in-browser/7282
=> fix(include): avoid segfault when calculating totalSize

packages/compare-images/python/itkwasm-compare-images-emscripten/pyproject.toml, packages/compare-images/python/itkwasm-compare-images-wasi/pyproject.toml, packages/compare-images/python/itkwasm-compare-images/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-emscripten/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify-wasi/pyproject.toml, packages/compress-stringify/python/itkwasm-compress-stringify/pyproject.toml, packages/core/python/itkwasm/test/test-accelerator/pyproject.toml, packages/core/typescript/itk-wasm/src/bindgen/python/resources/template.pyproject.toml, packages/core/typescript/itk-wasm/test/pipelines/bindgen-interface-types-pipeline/python/itkwasm-bindgen-interface-types-test-wasi/pyproject.toml, packages/core/typescript/itk-wasm/test/pipelines/bindgen-interface-types-pipeline/python/itkwasm-bindgen-interface-types-test/pyproject.toml, packages/dicom/python/itkwasm-dicom-emscripten/pyproject.toml, packages/dicom/python/itkwasm-dicom-wasi/pyproject.toml, packages/dicom/python/itkwasm-dicom/pyproject.toml, packages/downsample/python/itkwasm-downsample-cucim/pyproject.toml, packages/downsample/python/itkwasm-downsample-emscripten/pyproject.toml, packages/downsample/python/itkwasm-downsample-wasi/pyproject.toml, packages/downsample/python/itkwasm-downsample/pyproject.toml, packages/image-io/python/itkwasm-image-io-emscripten/pyproject.toml, packages/image-io/python/itkwasm-image-io-wasi/pyproject.toml, packages/image-io/python/itkwasm-image-io/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io-emscripten/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io-wasi/pyproject.toml, packages/mesh-io/python/itkwasm-mesh-io/pyproject.toml, packages/transform-io/python/itkwasm-transform-io-emscripten/pyproject.toml, packages/transform-io/python/itkwasm-transform-io-wasi/pyproject.toml, packages/transform-io/python/itkwasm-transform-io/pyproject.toml
`license` is deprecated in favor of `license-expression` with
pyproject.toml `metadata-version` 2.4 and newer.
Ref:
- https://peps.python.org/pep-0639/#term-license-expression
- https://packaging.python.org/en/latest/specifications/core-metadata/#license-expression
=> build(pyproject.toml): replace license with license-expression

packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/bindgen/canonical-type.js, packages/core/typescript/itk-wasm/src/bindgen/python/function-module-args.js, packages/core/typescript/itk-wasm/src/bindgen/python/wasi/wasi-function-module.js, packages/core/typescript/itk-wasm/src/bindgen/typescript/function-module.js, packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/template.package.json, packages/core/typescript/itk-wasm/src/version.ts, packages/core/typescript/itk-wasm/test/pipelines/input-output-json-pipeline/input-output-json-test.cxx
Future todo: handle these as string enums.
=> feat(bindgen): support string choices

packages/dicom/dcmtk/CMakeLists.txt
Through upstream patch:
https://github.com/QIICR/dcmqi/pull/511
=> build(dicom): ensure dcmqi finds pixi's Python

.github/workflows/scorecard.yml
Scans repository for security issues on push to the default branch.
See also:
- https://github.com/ossf/scorecard
- https://github.com/marketplace/actions/ossf-scorecard-action
=> ENH: Add OpenSSF Scorecard action

docs/development/hacking_itk_wasm.md, package.json, pixi.lock, pixi.toml, pnpm-lock.yaml
- build(native): install make
- build(native): move cmake and cxx-compiler to the default environment
- test(pixi): exclude create-itk-wasm from top level
- test(cypress): bump to 13.17.0 to address firefox connection issues
- docs(hacking-itk-wasm): update getting started requirements
=> ubuntu 24.04 deps

docs/development/hacking_itk_wasm.md, docs/introduction/packages.md
- docs(hacking): fix ITK-Wasm capitalization
- docs(packages): point to create-itk-wasm
=> docs create itk wasm

.github/workflows/examples.yml, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/index-worker-embedded.ts, packages/core/typescript/itk-wasm/tsconfig.json
For direct use in the browser as an ESM.
=> build(itk-wasm): generate index-wasm-worker-embedded.js

packages/core/python/itkwasm/itkwasm/polydata.py, packages/core/python/itkwasm/test/test_polydata.py
=> fix(polydata): add missing metadata in python dataclass

packages/compress-stringify/typescript/package.json, pnpm-lock.yaml
This is not needed for our workflow and introduces problems for demo
docs deployment.
=> build(compress-stringify): remove -build ts build dep

.github/workflows/cxx-python.yml, .github/workflows/python-wasm.yml
Workaround bugs in C++17 support.
Temporary workaround until #1354 is finalized.
=> ci(cxx): disable macos-13 build

packages/core/python/itkwasm/itkwasm/__init__.py, packages/core/python/itkwasm/itkwasm/image.py, packages/core/python/itkwasm/itkwasm/image_from_array.py, packages/core/python/itkwasm/pixi.lock, packages/core/python/itkwasm/pyproject.toml, packages/core/python/itkwasm/test/test_image.py, packages/core/python/itkwasm/test/test_image_from_array.py, packages/core/python/itkwasm/test/test_polydata.py
- docs(py): update author email
- fix(py): set initial buffered region with py constructed data
=> image from array buffered default

.github/workflows/cxx-python.yml
=> ci(cxx-python): set correct type for CMAKE_CXX_STANDARD

include/itkInputStreamBase.h, src/itkInputStreamBase.cxx
Simplified the class by removing its member variables m_DeleteIStream and m_WasmStringStream. Avoided manual memory management.
=> style: Use `std::unique_ptr<std::istream>` in InputStreamBase

packages/core/typescript/create-itk-wasm/package.json, packages/core/typescript/create-itk-wasm/src/generate/itk-wasm-env-bash.ts, packages/core/typescript/create-itk-wasm/src/generate/package-json.ts, packages/core/typescript/create-itk-wasm/src/generate/pixi-toml.ts, packages/core/typescript/itk-wasm/package.json, packages/core/typescript/itk-wasm/src/bindgen/typescript/resources/template.package.json, packages/core/typescript/itk-wasm/src/cli/default-image-tag.js, packages/core/typescript/itk-wasm/src/version.ts, src/docker/RELEASE.md, src/docker/itk-wasm-base/Dockerfile
- chore(create-itk-wasm): bump itk-wasm to 1.0.0-b.195
- chore(create-itk-wasm): bump version to 2.1.2
- chore(create-itk-wasm): bump ITK_WASM_ITK_BRANCH
=> create itk wasm bump

include/itkSupportInputImageTypes.h
Two small style improvements in `SupportInputImageTypes`, related to the use of `passThrough` variables.
=> Style improvements SupportInputImageTypes passThrough
